### ISSUE TITLE
Name missing

### ISSUE THREAD

**Issue by vasilisanagnostopoulos** [zoho/zohocrm-python-sdk-6.0#3]
When I try to use the initializer sample from here

https://www.zoho.com/crm/developer/docs/sdk/server-side/python-sdk.html

, for EU i always get

DataCenter.Environment.__init__() missing 1 required positional argument: 'name'

(US has us_prod)

is EU supported? I work for Newcross Healthcare. What is the correct datacenter?

**Comment by raja-7453** [comment]
@vasilisanagnostopoulos Please get in touch with support@zohocrm.com. We will follow up on this request, over there.

Thanks!

**Comment by raja-7453** [comment]
Thanks. @vasilisanagnostopoulos. This has been fixed in this [2.0.0](https://pypi.org/project/zohocrmsdk6-0/2.0.0/) release.
